//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Commit.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Commit.h"

#include <utility>

Commit::Commit(string uuid, string autor) {
    this->uuid = std::move(uuid);
    this->autor = std::move(autor);
}

string Commit::getUuid()  {
    return uuid;
}

string Commit::getAutor() {
    return autor;
}

