//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Commit.h
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#if !defined(_COMMIT_H)
#define _COMMIT_H

#include <string>
using namespace std;

class Commit {
public:
	Commit(string uuid, string autor);
	string getUuid();
	string getAutor();
private:
	string uuid;
	string autor;
};

#endif  //_COMMIT_H
