//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Repozytorium.h
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#if !defined(_REPOZYTORIUM_H)
#define _REPOZYTORIUM_H

#include <string>
#include <vector>
#include "Commit.h"
using namespace std;

class Repozytorium {
public:
	Repozytorium(string nazwaRepo, string wlasciciel, vector<Commit> commits);
	void zmienNazwe(string nazwa);
	string getNazwa();
	string getWlasciciel();
	vector<Commit> getCommity();
private:
	string nazwaRepo;
	string wlasciciel;
	vector<Commit> commits;
};

#endif  //_REPOZYTORIUM_H
