//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Repozytorium.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Repozytorium.h"

Repozytorium::Repozytorium(string nazwaRepo, string wlasciciel, vector<Commit> commits) {
    this->nazwaRepo = std::move(nazwaRepo);
    this->wlasciciel = std::move(wlasciciel);
    this->commits = std::move(commits);
}

vector<Commit> Repozytorium::getCommity() {
    return commits;
}

void Repozytorium::zmienNazwe(string nazwa) {
    this->nazwaRepo = std::move(nazwa);
}

string Repozytorium::getNazwa() {
    return nazwaRepo;
}

string Repozytorium::getWlasciciel() {
    return wlasciciel;
}

