//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serwer_testujacy.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Serwer_testujacy.h"

Serwer_testujacy::Serwer_testujacy(string adres) {
    this->adres = std::move(adres);
}

string Serwer_testujacy::getAdres() {
    return adres;
}

