//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serwer_testujacy.h
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#if !defined(_SERWER_TESTUJACY_H)
#define _SERWER_TESTUJACY_H

#include <string>
using namespace std;

class Serwer_testujacy {
public:
	Serwer_testujacy(string adres);
	string getAdres();
private:
	string adres;
};

#endif  //_SERWER_TESTUJACY_H
