//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.h
//  @ Date : 29.03.2026
//  @ Author : 
//
//


#if !defined(_BIBLIOTEKA_H)
#define _BIBLIOTEKA_H

#include <string>
#include <vector>
using namespace std;

#include "Ksiazka.h"

class Biblioteka {
public:
	Biblioteka(string nazwa, string adres);
	void zmienNazwe(string nazwa);
	string getNazwa();
	string getAdres();
	void dodajKsiazke(Ksiazka nowaKsiazka);
	void usunKsiazke(string isbn);
	vector<Ksiazka> getKsiazki();
private:
	string nazwa;
	string adres;
	vector<Ksiazka> ksiazki;
};

#endif  //_BIBLIOTEKA_H
