//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.cpp
//  @ Date : 29.03.2026
//  @ Author : 
//
//


#include "Biblioteka.h"
#include "Ksiazka.h"

Biblioteka::Biblioteka(string nazwa, string adres) {
    this->nazwa = nazwa;
    this->adres = adres;
}

void Biblioteka::zmienNazwe(string nazwa) {
    this->nazwa = nazwa;
}

string Biblioteka::getNazwa() {
    return nazwa;
}

string Biblioteka::getAdres() {
    return adres;
}

void Biblioteka::dodajKsiazke(Ksiazka nowaKsiazka) {
    ksiazki.push_back(nowaKsiazka);
}

void Biblioteka::usunKsiazke(string isbn) {
    for (auto it = ksiazki.begin(); it != ksiazki.end(); ++it) {
        if (it->getNumerISBN() == isbn) {
            ksiazki.erase(it);
            return;
        }
    }
}

vector<Ksiazka> Biblioteka::getKsiazki() {
    return ksiazki;
}
