//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.cpp
//  @ Date : 29.03.2026
//  @ Author : 
//
//


#include "Ksiazka.h"
#include "Rozdzial.h"

Ksiazka::Ksiazka(string tytul, string autor, string isbn) {
    this->tytul = tytul;
    this->autor = autor;
    this->numerISBN = isbn;
}

string Ksiazka::getTytul() {
    return tytul;
}

string Ksiazka::getAutor() {
    return autor;
}

string Ksiazka::getNumerISBN() {
    return numerISBN;
}

void Ksiazka::dodajRozdzial(Rozdzial nowyRozdzial) {
    rozdzialy.push_back(nowyRozdzial);
}

vector<Rozdzial> Ksiazka::getRozdzialy() {
    return rozdzialy;
}
