//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.h
//  @ Date : 29.03.2026
//  @ Author : 
//
//


#if !defined(_KSIAZKA_H)
#define _KSIAZKA_H

#include <string>
#include <vector>
using namespace std;

#include "Rozdzial.h"

class Ksiazka {
public:
	Ksiazka(string tytul, string autor, string isbn);
	string getTytul();
	string getAutor();
	string getNumerISBN();
	void dodajRozdzial(Rozdzial nowyRozdzial);
	vector<Rozdzial> getRozdzialy();
private:
	string tytul;
	string autor;
	string numerISBN;
	vector<Rozdzial> rozdzialy;
};

#endif  //_KSIAZKA_H
