//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rozdzial.h
//  @ Date : 29.03.2026
//  @ Author : 
//
//


#if !defined(_ROZDZIAL_H)
#define _ROZDZIAL_H

#include <string>
using namespace std;

class Rozdzial {
public:
	Rozdzial(int numer, string tytul, int strony);
	string getTytulRozdzialu();
	int getNumerRozdzialu();
	int getLiczbaStron();
private:
	string tytulRozdzialu;
	int numerRozdzialu;
	int liczbaStron;
};

#endif  //_ROZDZIAL_H
