//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rozdzial.cpp
//  @ Date : 29.03.2026
//  @ Author : 
//
//


#include "Rozdzial.h"

Rozdzial::Rozdzial(int numer, string tytul, int strony) {
    numerRozdzialu = numer;
    tytulRozdzialu = tytul;
    liczbaStron = strony;
}

string Rozdzial::getTytulRozdzialu() {
    return tytulRozdzialu;
}

int Rozdzial::getNumerRozdzialu() {
    return numerRozdzialu;
}

int Rozdzial::getLiczbaStron() {
    return liczbaStron;
}
