//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_CLIENT_H)
#define _CLIENT_H

#include "IVehicleFactory.h"
#include "IPassengerCar.h"
#include "IDeliveryVan.h"

class Client {
private:
	IVehicleFactory* factory;
	IPassengerCar* car;
	IDeliveryVan* van;
public:
	Client(IVehicleFactory* f) : factory(f), car(nullptr), van(nullptr) {}

	~Client() {
		delete car;
		delete van;
	}

	void createVehicles() {
		car = factory->createPassengerCar();
		van = factory->createDeliveryVan();
	}

	void useVehicles() {
		if(car) car->drive();
		if(van) van->deliver();
	}
};

#endif  //_CLIENT_H
