//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CombustionVehicleFactory.cpp
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#include "CombustionVehicleFactory.h"
#include "CombustionPassengerCar.h"
#include "CombustionDeliveryVan.h"

IPassengerCar* CombustionVehicleFactory::createPassengerCar() {
	return new CombustionPassengerCar();
}

IDeliveryVan* CombustionVehicleFactory::createDeliveryVan() {
	return new CombustionDeliveryVan();
}

