//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CombustionPassengerCar.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_COMBUSTIONPASSENGERCAR_H)
#define _COMBUSTIONPASSENGERCAR_H

#include "IPassengerCar.h"
#include <iostream>

class CombustionPassengerCar : public IPassengerCar {
public:
	void drive() override {
		std::cout << "Jazda samochodem osobowym spalinowym" << std::endl;
	}
};

#endif  //_COMBUSTIONPASSENGERCAR_H
