//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CombustionVehicleFactory.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_COMBUSTIONVEHICLEFACTORY_H)
#define _COMBUSTIONVEHICLEFACTORY_H

#include "IVehicleFactory.h"

class CombustionVehicleFactory : public IVehicleFactory {
public:
	IPassengerCar* createPassengerCar() override;
	IDeliveryVan* createDeliveryVan() override;
};

#endif  //_COMBUSTIONVEHICLEFACTORY_H
