//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CombustionDeliveryVan.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_COMBUSTIONDELIVERYVAN_H)
#define _COMBUSTIONDELIVERYVAN_H

#include "IDeliveryVan.h"
#include <iostream>

class CombustionDeliveryVan : public IDeliveryVan {
public:
	void deliver() override {
		std::cout << "Dostawa vanem spalinowym" << std::endl;
	}
};

#endif  //_COMBUSTIONDELIVERYVAN_H
