//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElectricVehicleFactory.cpp
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#include "ElectricVehicleFactory.h"
#include "ElectricPassengerCar.h"
#include "ElectricDeliveryVan.h"

IPassengerCar* ElectricVehicleFactory::createPassengerCar() {
	return new ElectricPassengerCar();
}

IDeliveryVan* ElectricVehicleFactory::createDeliveryVan() {
	return new ElectricDeliveryVan();
}

