//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElectricVehicleFactory.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_ELECTRICVEHICLEFACTORY_H)
#define _ELECTRICVEHICLEFACTORY_H

#include "IVehicleFactory.h"

class ElectricVehicleFactory : public IVehicleFactory {
public:
	IPassengerCar* createPassengerCar() override;
	IDeliveryVan* createDeliveryVan() override;
};

#endif  //_ELECTRICVEHICLEFACTORY_H
