//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElectricDeliveryVan.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_ELECTRICDELIVERYVAN_H)
#define _ELECTRICDELIVERYVAN_H

#include "IDeliveryVan.h"
#include <iostream>

class ElectricDeliveryVan : public IDeliveryVan {
public:
	void deliver() override {
		std::cout << "Dostawa vanem elektrycznym" << std::endl;
	}
};

#endif  //_ELECTRICDELIVERYVAN_H
