//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElectricPassengerCar.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_ELECTRICPASSENGERCAR_H)
#define _ELECTRICPASSENGERCAR_H

#include "IPassengerCar.h"
#include <iostream>

class ElectricPassengerCar : public IPassengerCar {
public:
	void drive() override {
		std::cout << "Jazda samochodem osobowym elektrycznym" << std::endl;
	}
};

#endif  //_ELECTRICPASSENGERCAR_H
