//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDeliveryVan.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_IDELIVERYVAN_H)
#define _IDELIVERYVAN_H


class IDeliveryVan {
public:
	virtual ~IDeliveryVan() = default;
	virtual void deliver() = 0;
};

#endif  //_IDELIVERYVAN_H
