//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IPassengerCar.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_IPASSENGERCAR_H)
#define _IPASSENGERCAR_H


class IPassengerCar {
public:
	virtual ~IPassengerCar() = default;
	virtual void drive() = 0;
};

#endif  //_IPASSENGERCAR_H
