//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IVehicleFactory.cpp
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#include "IVehicleFactory.h"


