//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IVehicleFactory.h
//  @ Date : 09.06.2026
//  @ Author : 
//
//


#if !defined(_IVEHICLEFACTORY_H)
#define _IVEHICLEFACTORY_H

class IPassengerCar;
class IDeliveryVan;

class IVehicleFactory {
public:
	virtual ~IVehicleFactory() = default;
	virtual IPassengerCar* createPassengerCar() = 0;
	virtual IDeliveryVan* createDeliveryVan() = 0;
};

#endif  //_IVEHICLEFACTORY_H
