//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.h
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#if !defined(_CLIENT_H)
#define _CLIENT_H

class Client {
public:
    void main();
};

#endif  //_CLIENT_H
