//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.cpp
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#include "Client.h"
#include "TRoom.h"
#include "TFireStation.h"
#include <iostream>

void Client::main() {
    TRoom room;
    TFireStation station;

    room.attach(&station);

    std::cout << "\n[Klient] Temperatura: 30 stopni C" << std::endl;
    room.setMeasurement(30);

    std::cout << "\n[Klient] Temperatura: 55 stopni C" << std::endl;
    room.setMeasurement(55);

    std::cout << "\n[Klient] Temperatura: 75 stopni C" << std::endl;
    room.setMeasurement(75);

    room.detach(&station);

    std::cout << "\n[Klient] Stacja odlaczona. Temperatura: 90 stopni C" << std::endl;
    room.setMeasurement(90);

    std::cout << "\n[Klient] Koniec testu." << std::endl;
}

int main() {
    Client client;
    client.main();
    return 0;
}
