//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserver.h
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#if !defined(_IOBSERVER_H)
#define _IOBSERVER_H


class TSubject;

class IObserver {
public:
    virtual void update(TSubject* subject) = 0;
    virtual ~IObserver() {}
};

#endif  //_IOBSERVER_H
