//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFireStation.h
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#if !defined(_TFIRESTATION_H)
#define _TFIRESTATION_H

#include "IObserver.h"

class TFireStation : public IObserver {
public:
    void update(TSubject* subject) override;
    void callFiretrucks();
};

#endif  //_TFIRESTATION_H
