//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFireStation.cpp
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#include "TFireStation.h"
#include "TRoom.h"
#include <iostream>

void TFireStation::update(TSubject* subject) {
    TRoom* room = dynamic_cast<TRoom*>(subject);
    if (room != nullptr) {
        std::cout << "[Stacja] Temperatura: " << room->getMeasurement() << " stopni C";
        if (room->getIsFire()) {
            std::cout << " - wykryto pozar!" << std::endl;
            callFiretrucks();
        } else {
            std::cout << " - brak pozaru." << std::endl;
        }
    }
}

void TFireStation::callFiretrucks() {
    std::cout << "[Stacja] Wysylanie wozow strazackich na miejsce!" << std::endl;
}
