//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TRoom.h
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#if !defined(_TROOM_H)
#define _TROOM_H

#include "TSubject.h"

class TRoom : public TSubject {
public:
	TRoom();
	void setMeasurement(int temp);
	int getMeasurement();
	bool getIsFire();
private:
	int temperature;
	bool isFire;
};

#endif  //_TROOM_H
