//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TRoom.cpp
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#include "TRoom.h"

TRoom::TRoom() : temperature(20), isFire(false) {}

void TRoom::setMeasurement(int temp) {
    temperature = temp;
    isFire = (temperature > 60);
    setChange();
    notify();
}

int TRoom::getMeasurement() {
    return temperature;
}

bool TRoom::getIsFire() {
    return isFire;
}
