//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSubject.h
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#if !defined(_TSUBJECT_H)
#define _TSUBJECT_H

#include <list>
#include "IObserver.h"

class TSubject {
public:
    TSubject();
    virtual ~TSubject();
    void attach(IObserver* observer);
    void detach(IObserver* observer);
    void notify();
    void setChange();
private:
    std::list<IObserver*> observers;
    bool change;
};

#endif  //_TSUBJECT_H
