//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSubject.cpp
//  @ Date : 15.06.2026
//  @ Author : 
//
//


#include "TSubject.h"

TSubject::TSubject() : change(false) {}

TSubject::~TSubject() {}

void TSubject::attach(IObserver* observer) {
    observers.push_back(observer);
}

void TSubject::detach(IObserver* observer) {
    observers.remove(observer);
}

void TSubject::notify() {
    if (change) {
        for (IObserver* obs : observers) {
            obs->update(this);
        }
        change = false;
    }
}

void TSubject::setChange() {
    change = true;
}
