//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"
#include <string>

using namespace std;

class Pies : public Ssak {
public:
	Pies(string imie, string rasa, string kolor, Ssak& ssak);
	void szczekanie();
	void machanieOgonem();
	void bieganie();
	string getImie();
	string getRasa();
	string getKolor();
private:
	string imie;
	string rasa;
	string kolor;
};

#endif  //_PIES_H
