//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#include "Pies.h"
#include <string>
#include <iostream>

using namespace std;

Pies::Pies(string imie, string rasa, string kolor, Ssak& ssak) : Ssak(ssak.getWiek(), ssak.getWaga()) {
    this->imie = imie;
    this->rasa = rasa;
    this->kolor = kolor;

}

void Pies::szczekanie() {
    cout << "Hau hau!" << endl;
}

void Pies::machanieOgonem() {
    cout << "*machanie ogonem*" << endl;
}

void Pies::bieganie() {
    cout << "*pies biega*" << endl;
}

string Pies::getImie() {
    return imie;
}

string Pies::getRasa() {
    return rasa;
}

string Pies::getKolor() {
    return kolor;
}

