//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#include "Ssak.h"
#include <iostream>

Ssak::Ssak(int wiek, int waga) {
    this->wiek = wiek;
    this->waga = waga;
}

void Ssak::jedzenie() {
    std::cout << "Ssak je." << std::endl;
}

void Ssak::picie() {
    std::cout << "Ssak pije." << std::endl;
}

void Ssak::oddychanie() {
    std::cout << "Ssak oddycha." << std::endl;
}

void Ssak::spanie() {
    std::cout << "Ssak spi." << std::endl;
}

int Ssak::getWiek() {
    return wiek;
}

int Ssak::getWaga() {
    return waga;
}
