//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H


class Ssak {
public:
	Ssak(int wiek, int waga);
	void jedzenie();
	void picie();
	void oddychanie();
	void spanie();
	int getWiek();
	int getWaga();
private:
	int wiek = 0;
	int waga;
};

#endif  //_SSAK_H
