//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H

#include <string>

using namespace std;

class Pracownik {
public:
	Pracownik(string imie, string nazwisko);
	string getImie();
	string getNazwisko();
private:
	string imie;
	string nazwisko;
};

#endif  //_PRACOWNIK_H
