//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Pracownik.h"
#include <string>

using namespace std;

Pracownik::Pracownik(string imie, string nazwisko) : imie(imie), nazwisko(nazwisko) {
}

string Pracownik::getImie() {
    return imie;
}

string Pracownik::getNazwisko() {
    return nazwisko;
}

