//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Programista.h
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#if !defined(_PROGRAMISTA_H)
#define _PROGRAMISTA_H

#include <string>

using namespace std;


class Programista {
public:
	Programista(string jezyk);
	void zmienJezyk(string jezyk);
	string getJezyk();
private:
	string jezykProgramowania;
};

#endif  //_PROGRAMISTA_H
