//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Programista.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Programista.h"
#include <string>

using namespace std;

Programista::Programista(string jezyk) : jezykProgramowania(jezyk) {
}

void Programista::zmienJezyk(string jezyk) {
    jezykProgramowania = jezyk;
}

string Programista::getJezyk() {
    return jezykProgramowania;
}

