//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zespol.h
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#if !defined(_ZESPOL_H)
#define _ZESPOL_H

#include <string>
#include <vector>
#include "Programista.h"

using namespace std;

class Zespol {
public:
	Zespol(string nazwaZespolu);
	void zmienNazwe(string nazwa);
	void dodajCzlonka(Programista &programista);
	void usunCzlonka(Programista &programista);
	int getIlosc();
	void wyswietlCzlonkow();
private:
	string nazwaZespolu;
	int iloscCzlonkow;
	vector<Programista*> czlonkowie;
};

#endif  //_ZESPOL_H
