//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zespol.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Zespol.h"
#include <iostream>
#include <string>

using namespace std;

Zespol::Zespol(string nazwaZespolu) : nazwaZespolu(nazwaZespolu), iloscCzlonkow(0) {
}

void Zespol::zmienNazwe(string nazwa) {
    nazwaZespolu = nazwa;
}

void Zespol::dodajCzlonka(Programista &programista) {
    czlonkowie.push_back(&programista);
    iloscCzlonkow++;
}

void Zespol::usunCzlonka(Programista &programista) {
    for (auto it = czlonkowie.begin(); it != czlonkowie.end(); ++it) {
        if (*it == &programista) {
            czlonkowie.erase(it);
            iloscCzlonkow--;
            break;
        }
    }
}

int Zespol::getIlosc() {
    return iloscCzlonkow;
}

void Zespol::wyswietlCzlonkow() {
    cout << "Zespol: " << nazwaZespolu << " (liczba czlonkow: " << iloscCzlonkow << ")" << endl;
    for (Programista* p : czlonkowie) {
        cout << "  - programista, jezyk: " << p->getJezyk() << endl;
    }
}

