//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Baza_danych_logowania.h
//  @ Date : 20.04.2026
//  @ Author : 
//
//


#if !defined(_BAZA_DANYCH_LOGOWANIA_H)
#define _BAZA_DANYCH_LOGOWANIA_H

#include <string>
#include <map>

class Baza_danych_logowania {
public:
    Baza_danych_logowania(const std::string& adresIp, const std::string& nazwaBazy);
    void polacz();
    void rozlacz();
    bool czyPolaczony();
    bool czyKontoIstnieje(const std::string& login);
    bool czyHasloPoprawne(const std::string& login, const std::string& haslo);
    void dodajUzytkownika(const std::string& login, const std::string& haslo);
private:
    std::string adresIp;
    std::string nazwaBazy;
    bool polaczono;
    std::map<std::string, std::string> uzytkownicy;
};

#endif  //_BAZA_DANYCH_LOGOWANIA_H
