//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Baza_danych_logowania.cpp
//  @ Date : 20.04.2026
//  @ Author : 
//
//


#include "Baza_danych_logowania.h"
#include <iostream>

Baza_danych_logowania::Baza_danych_logowania(const std::string& adresIp, const std::string& nazwaBazy)
    : adresIp(adresIp), nazwaBazy(nazwaBazy), polaczono(false) {
}

void Baza_danych_logowania::polacz() {
    polaczono = true;
    std::cout << "[Baza] Polaczono z baza: " << nazwaBazy << " @ " << adresIp << std::endl;
}

void Baza_danych_logowania::rozlacz() {
    polaczono = false;
    std::cout << "[Baza] Rozlaczono z baza." << std::endl;
}

bool Baza_danych_logowania::czyPolaczony() {
    return polaczono;
}

bool Baza_danych_logowania::czyKontoIstnieje(const std::string& login) {
    bool wynik = uzytkownicy.find(login) != uzytkownicy.end();
    std::cout << "[Baza] Sprawdzanie konta '" << login << "': " << (wynik ? "istnieje" : "nie istnieje") << std::endl;
    return wynik;
}

bool Baza_danych_logowania::czyHasloPoprawne(const std::string& login, const std::string& haslo) {
    auto it = uzytkownicy.find(login);
    bool wynik = (it != uzytkownicy.end() && it->second == haslo);
    std::cout << "[Baza] Sprawdzanie hasla dla '" << login << "': " << (wynik ? "poprawne" : "niepoprawne") << std::endl;
    return wynik;
}

void Baza_danych_logowania::dodajUzytkownika(const std::string& login, const std::string& haslo) {
    uzytkownicy[login] = haslo;
}
