//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kontroler.h
//  @ Date : 20.04.2026
//  @ Author : 
//
//


#if !defined(_KONTROLER_H)
#define _KONTROLER_H

#include <string>
#include "Baza_danych_logowania.h"

class Kontroler {
public:
    Kontroler(Baza_danych_logowania& baza, int limitBlednychProb = 3);
    void zlecLogowanie(const std::string& login, const std::string& haslo);
private:
    int limitBlednychProb;
    int licznikBledow;
    Baza_danych_logowania& baza;
};

#endif  //_KONTROLER_H
