//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kontroler.cpp
//  @ Date : 20.04.2026
//  @ Author : 
//
//


#include "Kontroler.h"
#include "Logowanie.h"
#include <iostream>

Kontroler::Kontroler(Baza_danych_logowania& baza, int limitBlednychProb)
    : baza(baza), limitBlednychProb(limitBlednychProb), licznikBledow(0) {
}

void Kontroler::zlecLogowanie(const std::string& login, const std::string& haslo) {
    std::cout << "\n[Kontroler] Zlecono logowanie dla: " << login << std::endl;

    if (licznikBledow >= limitBlednychProb) {
        std::cout << "[Kontroler] Konto zablokowane! Przekroczono limit " << limitBlednychProb << " blednych prob." << std::endl;
        return;
    }

    if (!baza.czyPolaczony()) {
        baza.polacz();
    }

    // Kontroler tworzy obiekt Logowanie i wywoluje autoryzuj()
    Logowanie log(login, haslo, baza);
    bool wynik = log.autoryzuj();

    if (wynik) {
        std::cout << "[Kontroler] Logowanie udane! Uzytkownik '" << login << "' zalogowany." << std::endl;
        licznikBledow = 0;
    } else {
        licznikBledow++;
        std::cout << "[Kontroler] Logowanie nieudane. Bledne proby: " << licznikBledow
                  << "/" << limitBlednychProb << std::endl;
    }
}
