//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Logowanie.cpp
//  @ Date : 20.04.2026
//  @ Author : 
//
//


#include "Logowanie.h"
#include <iostream>

Logowanie::Logowanie(const std::string& login, const std::string& haslo, Baza_danych_logowania& baza)
    : wprowadzonyLogin(login), wprowadzoneHaslo(haslo), czyUdane(false), baza(baza) {
    std::cout << "[Logowanie] Utworzono obiekt logowania dla uzytkownika: " << login << std::endl;
}

bool Logowanie::autoryzuj() {
    std::cout << "[Logowanie] Rozpoczynam autoryzacje..." << std::endl;

    if (!baza.czyKontoIstnieje(wprowadzonyLogin)) {
        std::cout << "[Logowanie] Konto nie istnieje. Autoryzacja nieudana." << std::endl;
        czyUdane = false;
        return false;
    }

    if (!baza.czyHasloPoprawne(wprowadzonyLogin, wprowadzoneHaslo)) {
        std::cout << "[Logowanie] Haslo niepoprawne. Autoryzacja nieudana." << std::endl;
        czyUdane = false;
        return false;
    }

    std::cout << "[Logowanie] Autoryzacja zakonczona sukcesem!" << std::endl;
    czyUdane = true;
    return true;
}
