//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Logowanie.h
//  @ Date : 20.04.2026
//  @ Author : 
//
//


#if !defined(_LOGOWANIE_H)
#define _LOGOWANIE_H

#include <string>
#include "Baza_danych_logowania.h"

class Logowanie {
public:
    Logowanie(const std::string& login, const std::string& haslo, Baza_danych_logowania& baza);
    bool autoryzuj();
private:
    std::string wprowadzonyLogin;
    std::string wprowadzoneHaslo;
    bool czyUdane;
    Baza_danych_logowania& baza;
};

#endif  //_LOGOWANIE_H
