//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBernouli.cpp
//  @ Date : 27.04.2026
//  @ Author : 
//
//


#include "TBernouli.h"
#include <iostream>

void TBernouli::bernouli(double p, int n, int k) {
    q = 1.0 - p;
    P = pNewton.newton(n, k) * pPower.power(p, k) * pPower.power(q, n - k);
    std::cout << "P(X=" << k << ") = " << (double) P << std::endl;
}

TBernouli::TBernouli() : q(0.0), P(0.0) {

}

TBernouli::~TBernouli() {

}

