//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFactorial.cpp
//  @ Date : 27.04.2026
//  @ Author : 
//
//


#include "TFactorial.h"

long double TFactorial::factorial(int n) {
    if (n <= 1) return 1;
    long double result = 1;
    for (int i = 2; i <= n; i++) {
        result *= i;
    }
    return result;
}

