//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TNewton.cpp
//  @ Date : 27.04.2026
//  @ Author : 
//
//


#include "TNewton.h"

long double TNewton::newton(int n, int k) {
    return pFactorial.factorial(n) /
           (pFactorial.factorial(k) * pFactorial.factorial(n - k));
}

TNewton::TNewton() : N(0) {

}

TNewton::~TNewton() {

}

