//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPower.cpp
//  @ Date : 27.04.2026
//  @ Author : 
//
//


#include "TPower.h"

double TPower::power(double n, int m) {
    double result = 1.0;
    for (int i = 0; i < m; i++) {
        result *= n;
    }
    return result;
}

